#!/bin/bash

shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

pth_download="$(echo -- curl "$@" | perl -ne 'm{-o\s+(\S+)} && print "$1"')"
nm_download="$(basename $pth_download)"

if [[ -f "$shome/vendor/cache/rvm/$nm_download" ]]; then
  rsync -ia "$shome/vendor/cache/rvm/$nm_download" "$pth_download"
else
  echo -- XXX curl "$@" 1>&2
  exec "$(type -a curl | grep '^curl is /' | tail -n +2 | head -1 | awk '{print $NF}')" -s -S "$@"
fi
