#!/bin/bash

nm_ruby="$1"; shift
ver_bundler="$1"; shift

if [[ "$EUID" = 0 ]]; then
  source /etc/profile.d/rvm.sh
else
  source ~/.rvm/scripts/rvm
fi

rvm uninstall "$nm_ruby" || true
rvm install "$nm_ruby" --disable-binary --skip-gemsets
echo yes | rvm-exec "$nm_ruby" rvm gemset delete global || true
rvm prepare "$nm_ruby" --install
rvm uninstall "$nm_ruby"
set +f; rvm mount --skip-gemsets -r ./*${nm_ruby}-*.tar.bz2; set -f
rvm-exec "$nm_ruby" gem list
rvm-exec "$nm_ruby" gem install bundler -v "$ver_bundler"
