#!/bin/bash

ver_rvm="$1"; shift

shome=$(pwd)
PATH="$shome/sbin:$PATH"

$shome/vendor/projects/rvm/rvm-installer --version $ver_rvm --without-gems="rvm rubygems-bundler" --ignore-dotfiles --quiet-curl
