#!/bin/bash

nm_ruby="$1"; shift
ver_bundler="$1"; shift

PATH="$PATH:/usr/local/rvm/bin:$HOME/.rvm/bin"

rvm install "$nm_ruby" --disable-binary --skip-gemsets
rvm prepare "$nm_ruby" --install
rvm uninstall "$nm_ruby"
set +f; rvm mount --skip-gemsets -r ./*${nm_ruby}-*.tar.bz2; set -f
rvm-exec "$nm_ruby" gem list
rvm-exec "$nm_ruby" gem install bundler -v "$ver_bundler"
